services:
  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stoik
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
